server:
  port: 9090

spring:
  application:
    name: message-store

rabbitmq:
  host: localhost
  port: 5672
  username: admin
  password: admin

data:
  mongodb:
    host: localhost
    port: 27017
    database: message_store		
